services:
  postgres:
    image: postgres:16-alpine
    container_name: bd_snowflake_postgres
    environment:
      POSTGRES_DB: snowflake_lab
      POSTGRES_USER: lab
      POSTGRES_PASSWORD: lab
      TZ: Europe/Moscow
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - "./исходные данные:/data:ro"
      - "./sql/init:/docker-entrypoint-initdb.d:ro"
      - "./sql/dw:/sql/dw:ro"
    healthcheck:
      test: ["CMD-SHELL", "psql -U lab -d snowflake_lab -tAc \"select count(*) = 10000 from dw.fact_sales\" | grep -q t"]
      interval: 5s
      timeout: 5s
      retries: 12

volumes:
  pgdata:
